version: '3.7'

services:
  splunk:
    image: splunk/splunk:latest
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_USER: "root"
      SPLUNK_PASSWORD: "SuperSecurePassword"
      SPLUNK_HEC_TOKEN: "abc123"
      SPLUNK_HTTP_PORT: "8000"
    ports:
      - "8000:8000"
      - "8088:8088"
    volumes:
      - "splunk_data:/opt/splunk/var/lib/splunk"
      - "splunk_logs:/opt/splunk/var/log/splunk"
      - "splunk_etc:/opt/splunk/etc"
    restart: always

  # fluent:
  #   build: fluent-bit
  #   volumes:
  #     - ./fluent-bit/fluent-bit.conf:/opt/fluent-bit/fluent-bit.conf
  #   depends_on:
  #     splunk:
  #       condition: "service_started"
    
volumes:
  splunk_data:
  splunk_logs:
  splunk_etc:
