version: '3.7'

services:
  mongodb:
    image: "mongo:5.0"
    volumes:
      - "mongodb_data:/data/db"
    restart: "on-failure"

  opensearch:
    image: "opensearchproject/opensearch:2.4.0"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "os_data:/usr/share/opensearch/data"
    restart: "on-failure"

  graylog:
    hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog-enterprise:5.0}"
    depends_on:
      opensearch:
        condition: "service_started"
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: "tBIE8uiNnElZQMbsX5WxCPhPxiV1fowmQIxEOMdvsmb67f160p6Astqw1nvmKXJTZVh3DAviNi1bqWDU3zBtGMxQPEHzIg03" # pwgen -N 1 -s 96
      GRAYLOG_ROOT_PASSWORD_SHA2: "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8" #  echo -n password | shasum -a 256 
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      # To make reporting (headless_shell) work inside a Docker container
      GRAYLOG_REPORT_DISABLE_SANDBOX: "true"
      GRAYLOG_SKIP_PREFLIGHT_CHECKS: 'true'
      # MESSAGE_JOURNAL_MAX_SIZE: 2gb
      GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE: 12gb
    ports:
      - "5044:5044/tcp" # Beats
      - "5140:5140/tcp" # Syslog TCP
      - "5140:5140/udp" # Syslog UDP
      - "5555:5555/tcp" # RAW TCP
      - "5555:5555/udp" # RAW TCP
      - "9000:9000/tcp" # Server API
      - "12201:12201/tcp" # GELF TCP
      - "12201:12201/udp" # GELF UDP
      #- "10000:10000/tcp" # Custom TCP port
      #- "10000:10000/udp" # Custom UDP port
      - "13301:13301/tcp" # Forwarder data
      - "13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    restart: "on-failure"


  # fluent:
  #   build: fluent-bit-graylog
  #   volumes:
  #     - ./fluent-bit-graylog/fluent-bit.conf:/opt/fluent-bit/fluent-bit.conf
  #   depends_on:
  #     graylog:
  #       condition: "service_started"
    


volumes:
  mongodb_data:
  os_data:
  graylog_data:
  graylog_journal:

networks:
   default:
      external:
         name: graylog_network